### PR TITLE
Remove all internal folders

### LINKED ISSUE #197: Remove all the internal folders
Looking at the [Cosmos codebase](https://github.com/cosmos/cosmos-sdk) it looks like they are finally getting rid of all the `/internal` folders. I think we should definitely follow this path as well, removing also the `alias.go` files.

### PR DESCRIPTION
**Pull request by bragaz**
## Description
This PR removes all the  modules' `internal` folders.
Closes #197.
## Checklist
- [x] Targeted PR against correct branch.
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote unit tests.
- [ ] Wrote integration tests (simulation & CLI). 
- [ ] Updated the documentation. 
- [x] Added an entry to the `CHANGELOG.md` file.
- [x] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

**Comment by RiccardoM** [comment]
@bragaz Looks like there are some conflicts here

**Comment by RiccardoM** [comment]
@bragaz A lot of conflicts have emerged :joy:

**Comment by bragaz** [comment]
@RiccardoM solved

**Comment by RiccardoM** [comment]
@bragaz can you solve (once again) the different conflicts please? :pray: I'll make sure to merge this afterwards

**Pull request merged**
