### PR TITLE
Updated Cosmos & Changed files structure

### LINKED ISSUE #10: Update Cosmos SDK to v0.37.0
With fixes and NFT

### PR DESCRIPTION
**Pull request by RiccardoM**
## Changes
- Updated Cosmos to v0.37.0 (closes #10)
- Changed the file structure to encapsulate internal stuff into the new `internal` folder

### CODE REVIEW

**Comment by kwunyeung** [comment]
There is a panic when I test the PR.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x46c65c5]

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/store/types.(*TransientStoreKey).Name(0x0, 0xc000985a10, 0xc0003dfb10)
	/Users/kwunyueng/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.3/store/types/store.go:261 +0x5
github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).MountStoreWithDB(0xc0001e0500, 0x50f6c20, 0x0, 0x3, 0x0, 0x0)
	/Users/kwunyueng/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.3/store/rootmulti/store.go:82 +0xb8
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).MountStore(...)
	/Users/kwunyueng/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.3/baseapp/baseapp.go:198
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).MountStores(0xc000510d80, 0xc0003e1298, 0xb, 0xb)
	/Users/kwunyueng/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.3/baseapp/baseapp.go:160 +0x164
github.com/kwunyeung/desmos.NewDesmosApp(0x5105f60, 0xc000166aa0, 0x5117b80, 0xc0000d00d8, 0x0, 0x0, 0x0, 0x4)
	/Users/kwunyueng/Projects/desmos/app.go:268 +0x32c4
main.newApp(0x5105f60, 0xc000166aa0, 0x5117b80, 0xc0000d00d8, 0x0, 0x0, 0xc0000b3f20, 0x9c)
	/Users/kwunyueng/Projects/desmos/cmd/desmosd/main.go:65 +0x5a
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc00099f060, 0x4f4cd80, 0x1d, 0x0, 0x0)
	/Users/kwunyueng/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.3/server/start.go:142 +0x134
github.com/cosmos/cosmos-sdk/server.StartCmd.func1(0xc00050f180, 0x5940b38, 0x0, 0x0, 0x0, 0x0)
	/Users/kwunyueng/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.3/server/start.go:65 +0xb4
github.com/spf13/cobra.(*Command).execute(0xc00050f180, 0x5940b38, 0x0, 0x0, 0xc00050f180, 0x5940b38)
	/Users/kwunyueng/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc00012a780, 0x2, 0xc00099f360, 0x4d77a76)
	/Users/kwunyueng/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/kwunyueng/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc00012a780, 0x4f4d190, 0x2, 0xc000038540)
	/Users/kwunyueng/go/pkg/mod/github.com/tendermint/tendermint@v0.32.6/libs/cli/setup.go:89 +0x3c
main.main()
	/Users/kwunyueng/Projects/desmos/cmd/desmosd/main.go:58 +0x3cc
```
I guess the way of mounting the stores is different. Please take a look.

**Comment by kwunyeung** [comment]
fixes #15

**Comment by RiccardoM** [comment]
Should be fixed @kwunyeung. Thanks for pointing out. We should have a unit test for that

**Comment by kwunyeung** [comment]
Let's start to have this habit now and add CI/CD to the repo.

**Comment by RiccardoM** [comment]
@kwunyeung I've opened #27 for this. Can we get this merged as it will allow people to write tests easier than the current code structure?

**Pull request merged**
